config/routes.rb
LendReminder::Application.routes.draw do

  match "/auth/:provider/callback", :to => "sessions#create"
  get "signup" => "users#new", as: :signup
  resources :users 
  resources :lend_records do
      get :remind, on: :collection
      get :canceled, on: :member
  end
  root to: "lend_records#index"
  get "login" => "sessions#new", as: :log_in
  match "logout" => "sessions#destroy", as: :log_out 
  resources :sessions
  resources :password_resets
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :provider, :uid
  validates :provider, presence: true, uniqueness: {scope: :user_id}
  validates :uid, presence: true, uniqueness: {scope: :provider}
  belongs_to :user
end

app/models/lend_record.rb
class LendRecord < ActiveRecord::Base
  attr_accessible :amount, :date, :email, :name
  belongs_to :user
  def self.to_csv(options={})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |record|
        csv << record.attributes.values_at(*column_names)
      end
    end
  end
  def self.check_date
    LendRecord.all.each do |record|
      if record.cancel == false && record.date <= Date.today
          RemindMailer.remind_email(record).deliver
      end
    end
  end
  
  def cancel_the_record
    self.cancel = true
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  has_many :lend_records
  has_many :authentications
  validates_presence_of :password, on: :create
  before_create {generate_token(:auth_token)}

  def add_auth(auth)
    authentications.create(provider: auth[:provider], uid: auth[:uid])
  end

  class << self
    def from_auth(auth)
      locate_auth(auth) || locate_email(auth) || create_user(auth)
    end

    def locate_auth(auth)
      Authentication.find_by_provider_and_uid(auth[:provider], auth[:uid]).try(:user)
    end

    def locate_email(auth)
      user = find_by_email(auth[:info][:email])
      return unless user
      user.add_auth(auth)
      user
    end

    def create_user(auth)
      user = create!(name: auth[:info][:nickname],
                     email: auth[:info][:email],
                     password: Time.now.to_s)
      user.add_auth
      user
    end
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authorize
  helper_method :current_user


 private 
  def current_user
    @current_user ||= User.find_by_auth_token(cookies[:auth_token]) if cookies[:auth_token]
  end

 def authorize
   redirect_to log_in_path, notice: "Please log in or sign up!" if current_user.nil?
 end
end

app/controllers/lend_records_controller.rb
class LendRecordsController < ApplicationController
  def index
    @user = current_user
    @search = @user.lend_records.search(params[:q])
    @lend_records = @search.result
    @lend_records = @lend_records.page(params[:page]).per(4)
    respond_to do |format|
      format.html
      format.csv{send_data @search.result.to_csv}
      format.xls
    end
  end
  def new
    @user = current_user
    @lend_record = LendRecord.new
  end
  def create
   params[:lend_record][:date] = Date.today.next_month if params[:lend_record][:date].empty?
    @user = current_user
    @lend_record = @user.lend_records.new(params[:lend_record])
    if @lend_record.save
      redirect_to @lend_record, notice: "Successfully created the record."
    else 
      render :new
    end
  end
  def show
    @user = current_user
    @lend_record = @user.lend_records.find(params[:id])
  end
  def edit
    @user = current_user
    @lend_record = @user.lend_records.find(params[:id])
  end
  def update
    @user = current_user
    @lend_record = @user.lend_records.find(params[:id])
    if @lend_record.update_attributes(params[:lend_record])
      redirect_to @lend_record, notice: "Successfully updated the record."
    else
      render :edit
    end
  end
  def destroy
    @user = current_user 
    @lend_record = @user.lend_records.find(params[:id])
    @lend_record.destroy
    redirect_to lend_records_path, notice: "Successfully destroyed the record."
  end

  def canceled 
    @user = current_user
    @lend_record = @user.lend_records.find(params[:id])
    @lend_record.cancel_the_record
    @lend_record.save
    redirect_to lend_records_path, notice: "Successfully canceled the record!"
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_filter :authorize
  def create
    user = User.find_by_email(params[:email]) 
    user.send_password_reset if user
    redirect_to log_in_path, notice: "Email sent with password reset."
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, alert: "Password &crarr;
      reset has expired."
    elsif @user.update_attributes(params[:user])
      redirect_to log_in_path, notice: "Password has been reset."
    else
      render :edit
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize
  def create
    if request.env['omniauth.auth']
      user = User.from_auth(request.env['omniauth.auth'])
      cookies[:auth_token] = user.auth_token
      redirect_to root_url, notice: "Successfully log in welcome #{user.name}."
    else
      user = User.find_by_email(params[:email])
      if user && user.authenticate(params[:password])
        if params[:remember_me] 
          cookies.permanent[:auth_token] = user.auth_token
        else
          cookies[:auth_token] = user.auth_token
        end
        redirect_to lend_records_path, notice: "Successfully log in!"
      else
        flash.now.alert = "Invalid email or password!"
        render :new
      end
    end
  end

  def destroy
    cookies.delete(:auth_token)
    redirect_to new_session_path, notice: "Successfully log out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user
      redirect_to lend_records_path,notice: "fjdkafda"
    else
      flash.now.alert = "hh"
      render :new
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lend_records_helper.rb
module LendRecordsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>LendReminder</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body> 
<div class="container">
  <%= flash[:notice] %>
  <%= yield %>
</div>
</body>
</html>

app/views/lend_records/_form.html.erb
<%= form_for @lend_record  do |f| %>
  <div>
    <% if @lend_record.errors.any? %>
      <h2><%= pluralize(@lend_record.errors.count, "error") %>prohibit this record to create!</h2>
      <ul>
        <% for @lend_record.errors.full_messages in error %>
          <li><%= error %></li>
        <% end %>
      </ul>
    <% end %>
  </div> 

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>
  <div>
    <%= f.label :date %>
    <%= f.text_field :date %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/lend_records/edit.html.erb
<h1>Edit the Record</h1>
<%= render "form" %>
<p>
  <%= link_to "Back to list", lend_records_path %> |
  <%= link_to "Show", @lend_record %>
</p>

app/views/lend_records/index.html.erb
<center>
  <%= link_to "log out", log_out_path, confirm: "Are you sure?", method: :delete %>

  <%= search_form_for @search, url: lend_records_path do |f| %>
    <div class="field">
    <%= f.label :name_cont, "Name" %>
    <%= f.text_field :name_cont %>
  </div>
  <div class="field">
    <%= f.label :email_cont, "Email" %>
    <%= f.email_field :email_cont %>
  </div>
  <div class="field">
    <%= f.label :amount_gteq, "Price" %>
    <%= f.text_field :amount_gteq %>
    <%= f.label :amount_lteq, "-" %>
    <%= f.text_field :amount_lteq %>
  </div>
  <div class="field">
    <%= f.label :date_gteq, "Date"%>
    <%= f.text_field :date_gteq %>
    <%= f.label :date_lteq, "-" %>
    <%= f.text_field :date_lteq %>
  </div>
  <div class="actions">
    <%= f.submit "Search" %>
  </div>
<% end %>
  <h1>The Lend Record</h1>
  <p>
  Download:
  <%= link_to "CSV", lend_records_path(format: "csv") %> |
  <%= link_to "Excel", lend_records_path(format: "xls") %>
  </p>


  <table>
    <tr>
      <th><%= sort_link(@search, :name, "Name") %></th>
      <th><%= sort_link(@search, :email, "Email") %></th>
      <th><%= sort_link(@search, :amount, "Amount") %></th>
      <th><%= sort_link(@search, :date, "Date") %></th>
    </tr>
    <% if @lend_records.empty? %>
      There is no record
  <% else %>
      <% @lend_records.each do |lend_record| %>
      <tr>
      <td ><%= lend_record.name %></td>
      <td ><%= lend_record.email %></td>
      <td><%= number_to_currency lend_record.amount %></td>
      <td><%= lend_record.date %></td>
      <td><%= link_to "Edit", edit_lend_record_path(lend_record) %></td>
      <td><%= link_to "show", lend_record %></td>
      <td><%= link_to "destroy", lend_record, confirm: "Are you sure?", method: :delete %></td>
      <% if lend_record.cancel == false %>
        <td><%= link_to "cancel", canceled_lend_record_path(lend_record), confirm: "Are you sure?" %></td>
    <% else %>
        <td>cancelled</td>
    <% end %>
    </tr>
  <% end %>
  <% end %>
  </table>
  <%= paginate @lend_records%>
  <%= link_to "New Record", new_lend_record_path %>
</center>

app/views/lend_records/index.xls.erb
<table border="1">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Amount</th>
    <th>Date</th>
    </tr>

    <% @search.result.each do |record| %>
      <tr>
        <td><%= record.name %></td>
        <td><%= record.email %></td>
        <td><%= record.amount %></td>
        <td><%= record.date %></td>
        </tr>
        <% end %>
  
</table>

app/views/lend_records/new.html.erb
<h1>The new lend record</h1>
<%= render "form" %>
<%= link_to "Back to list", lend_records_path %>

app/views/lend_records/show.html.erb
<h1>Show the record</h1>
<p>Name:<%= @lend_record.name %></p>
<p>Email:<%= @lend_record.email %></p>
<p>Amount:<%= number_to_currency @lend_record.amount %></p>
<p>Date: <%= @lend_record.date %></p>
<%= link_to "Edit", edit_lend_record_path(@lend_record) %>
<%= link_to "Back to list", lend_records_path %>

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>
<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Update Password" %>
<% end %>

app/views/password_resets/new.html.erb
<h1>PasswordResets#new</h1>
<%= form_tag password_resets_path do %>
  <%= label_tag :email %>
  <%= email_field_tag :email, params[:email] %>
  <%= submit_tag "Reset Password" %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name %><br />
  <%= f.text_field :name %><br />
  <%= f.label :email %><br />
  <%= f.email_field :email %><br />
  <%= f.label :password %><br />
  <%= f.password_field :password %><br />
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %><br />
  <%= f.submit  %>
<% end %>